apiVersion: apps/v1
kind: Deployment
metadata:
   name: kube
spec:
   selector:
     matchLabels:
       app: kube
   replicas: 1
   template:
     metadata:
       labels:
         app: kube
     spec:
       containers:
       - name: flaskapp
         image: brinkley182/flaskapp
         ports:
         - containerPort: 8432
